#!/bin/bash

# start minekube using docker driver
minikube start --driver=docker

# Verify status of cluster
minekube status

# Check cluster info
kubectl cluster-info

# Retrieve the available pods
kubectl get pods
